name: Deploy to Pages

on:
    push:
        branches: [main, ci-testing] # branch to trigger deployment

jobs:
    pages:
        # TODO: run on self-hosted?
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        permissions:
            pages: write
            id-token: write
        steps:
            - id: deployment
              uses: sphinx-notes/pages@v3
